/*
 * GeneratorView.java
 */

package de.unibw.prdg.gui;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;

import de.unibw.prdg.PseudoRandomDataGenerator;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

import javax.print.attribute.TextSyntax;
import javax.swing.JFileChooser;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * The application's main frame.
 */
public class GeneratorView extends FrameView {

    private JFileChooser generatorFileChooser;

	public GeneratorView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = GeneratorApp.getApplication().getMainFrame();
            aboutBox = new GeneratorAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        GeneratorApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	generatorFileChooser = new javax.swing.JFileChooser();
    	generatorFileChooser.setCurrentDirectory(new java.io.File("data"));
    	generatorFileChooser.setDialogTitle("Erzeugten Datensatz speichern");
    	generatorFileChooser.setFileFilter(new FileNameExtensionFilter(
                        "INT-Dateien", "int"));
        mainPanel = new javax.swing.JPanel();
        panelZeitraum = new javax.swing.JPanel();
        labelZeitraum = new javax.swing.JLabel();
        labelZeitraumBeginn = new javax.swing.JLabel();
        labelZeitraumEnde = new javax.swing.JLabel();
        textZeitraumBeginn = new javax.swing.JTextField();
        textZeitraumEnde = new javax.swing.JTextField();
        labelAnzahl = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        panelParameter = new javax.swing.JPanel();
        labelParameter = new javax.swing.JLabel();
        labelParameterBeginn = new javax.swing.JLabel();
        labelParameterDauer = new javax.swing.JLabel();
        comboBoxParameterBeginnVerteilung = new javax.swing.JComboBox();
        labelParameterBeginnMittel = new javax.swing.JLabel();
        labelParameterBeginnVarianz = new javax.swing.JLabel();
        textParameterBeginnVarianz = new javax.swing.JTextField();
        textParameterBeginnMittel = new javax.swing.JTextField();
        comboBoxParameterDauerVerteilung = new javax.swing.JComboBox();
        labelParameterDauerA = new javax.swing.JLabel();
        textParameterDauerA = new javax.swing.JTextField();
        labelParameterDauerB = new javax.swing.JLabel();
        textParameterDauerB = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        buttonErzeugen = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.BorderLayout());

        panelZeitraum.setName("panelZeitraum"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(de.unibw.prdg.gui.GeneratorApp.class).getContext().getResourceMap(GeneratorView.class);
        labelZeitraum.setFont(resourceMap.getFont("labelZeitraum.font")); // NOI18N
        labelZeitraum.setText(resourceMap.getString("labelZeitraum.text")); // NOI18N
        labelZeitraum.setName("labelZeitraum"); // NOI18N

        labelZeitraumBeginn.setText(resourceMap.getString("labelZeitraumBeginn.text")); // NOI18N
        labelZeitraumBeginn.setName("labelZeitraumBeginn"); // NOI18N

        labelZeitraumEnde.setText(resourceMap.getString("labelZeitraumEnde.text")); // NOI18N
        labelZeitraumEnde.setName("labelZeitraumEnde"); // NOI18N

        textZeitraumBeginn.setText(resourceMap.getString("textZeitraumBeginn.text")); // NOI18N
        textZeitraumBeginn.setName("textZeitraumBeginn"); // NOI18N
        textZeitraumBeginn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textZeitraumBeginnActionPerformed(evt);
            }
        });

        textZeitraumEnde.setText(resourceMap.getString("textZeitraumEnde.text")); // NOI18N
        textZeitraumEnde.setName("textZeitraumEnde"); // NOI18N
        textZeitraumEnde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textZeitraumEndeActionPerformed(evt);
            }
        });

        labelAnzahl.setText(resourceMap.getString("labelAnzahl.text")); // NOI18N
        labelAnzahl.setName("labelAnzahl"); // NOI18N

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N

        javax.swing.GroupLayout panelZeitraumLayout = new javax.swing.GroupLayout(panelZeitraum);
        panelZeitraum.setLayout(panelZeitraumLayout);
        panelZeitraumLayout.setHorizontalGroup(
            panelZeitraumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelZeitraumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelZeitraumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelZeitraumEnde)
                    .addComponent(labelZeitraumBeginn)
                    .addComponent(labelZeitraum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelZeitraumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textZeitraumBeginn)
                    .addComponent(textZeitraumEnde, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelAnzahl)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        panelZeitraumLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField2, textZeitraumBeginn, textZeitraumEnde});

        panelZeitraumLayout.setVerticalGroup(
            panelZeitraumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelZeitraumLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelZeitraum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelZeitraumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZeitraumBeginn)
                    .addComponent(textZeitraumBeginn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAnzahl)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelZeitraumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelZeitraumEnde)
                    .addComponent(textZeitraumEnde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainPanel.add(panelZeitraum, java.awt.BorderLayout.PAGE_START);

        panelParameter.setName("panelParameter"); // NOI18N

        labelParameter.setFont(resourceMap.getFont("labelParameter.font")); // NOI18N
        labelParameter.setText(resourceMap.getString("labelParameter.text")); // NOI18N
        labelParameter.setName("labelParameter"); // NOI18N

        labelParameterBeginn.setText(resourceMap.getString("labelParameterBeginn.text")); // NOI18N
        labelParameterBeginn.setName("labelParameterBeginn"); // NOI18N

        labelParameterDauer.setText(resourceMap.getString("labelParameterDauer.text")); // NOI18N
        labelParameterDauer.setName("labelParameterDauer"); // NOI18N

        comboBoxParameterBeginnVerteilung.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normalverteilung", "Gleichverteilung" }));
        comboBoxParameterBeginnVerteilung.setName("comboBoxParameterBeginnVerteilung"); // NOI18N
        comboBoxParameterBeginnVerteilung.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                changeVerteilung(evt);
            }
        });
        comboBoxParameterBeginnVerteilung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionBeginnVerteilung(evt);
            }
        });

        labelParameterBeginnMittel.setText(resourceMap.getString("labelParameterBeginnMittel.text")); // NOI18N
        labelParameterBeginnMittel.setName("labelParameterBeginnMittel"); // NOI18N

        labelParameterBeginnVarianz.setText(resourceMap.getString("labelParameterBeginnVarianz.text")); // NOI18N
        labelParameterBeginnVarianz.setName("labelParameterBeginnVarianz"); // NOI18N

        textParameterBeginnVarianz.setText(resourceMap.getString("textParameterBeginnVarianz.text")); // NOI18N
        textParameterBeginnVarianz.setName("textParameterBeginnVarianz"); // NOI18N
        textParameterBeginnVarianz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textParameterBeginnVarianzActionPerformed(evt);
            }
        });

        textParameterBeginnMittel.setText(resourceMap.getString("textParameterBeginnMittel.text")); // NOI18N
        textParameterBeginnMittel.setName("textParameterBeginnMittel"); // NOI18N
        textParameterBeginnMittel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textParameterBeginnMittelActionPerformed(evt);
            }
        });

        comboBoxParameterDauerVerteilung.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normalverteilung", "Gleichverteilung" }));
        comboBoxParameterDauerVerteilung.setName("comboBoxParameterDauerVerteilung"); // NOI18N
        comboBoxParameterDauerVerteilung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxParameterDauerVerteilungActionPerformed(evt);
            }
        });

        labelParameterDauerA.setText(resourceMap.getString("labelParameterDauerA.text")); // NOI18N
        labelParameterDauerA.setName("labelParameterDauerA"); // NOI18N

        textParameterDauerA.setText(resourceMap.getString("textParameterDauerA.text")); // NOI18N
        textParameterDauerA.setName("textParameterDauerA"); // NOI18N
        textParameterDauerA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textParameterDauerAActionPerformed(evt);
            }
        });

        labelParameterDauerB.setText(resourceMap.getString("labelParameterDauerB.text")); // NOI18N
        labelParameterDauerB.setName("labelParameterDauerB"); // NOI18N

        textParameterDauerB.setText(resourceMap.getString("textParameterDauerB.text")); // NOI18N
        textParameterDauerB.setName("textParameterDauerB"); // NOI18N
        textParameterDauerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textParameterDauerBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelParameterLayout = new javax.swing.GroupLayout(panelParameter);
        panelParameter.setLayout(panelParameterLayout);
        panelParameterLayout.setHorizontalGroup(
            panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParameterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelParameterBeginnVarianz)
                    .addGroup(panelParameterLayout.createSequentialGroup()
                        .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelParameter, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelParameterBeginn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelParameterDauer, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelParameterLayout.createSequentialGroup()
                                .addComponent(comboBoxParameterBeginnVerteilung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelParameterBeginnMittel))
                            .addGroup(panelParameterLayout.createSequentialGroup()
                                .addComponent(comboBoxParameterDauerVerteilung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelParameterDauerA))))
                    .addComponent(labelParameterDauerB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textParameterDauerA, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textParameterDauerB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(textParameterBeginnVarianz, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(textParameterBeginnMittel))
                .addContainerGap())
        );
        panelParameterLayout.setVerticalGroup(
            panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParameterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelParameter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelParameterBeginn)
                    .addComponent(comboBoxParameterBeginnVerteilung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelParameterBeginnMittel)
                    .addComponent(textParameterBeginnMittel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelParameterBeginnVarianz)
                    .addComponent(textParameterBeginnVarianz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelParameterDauer)
                    .addComponent(comboBoxParameterDauerVerteilung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelParameterDauerA)
                    .addComponent(textParameterDauerA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelParameterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelParameterDauerB)
                    .addComponent(textParameterDauerB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(panelParameter, java.awt.BorderLayout.CENTER);

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        buttonErzeugen.setText(resourceMap.getString("buttonErzeugen.text")); // NOI18N
        buttonErzeugen.setName("buttonErzeugen"); // NOI18N
        buttonErzeugen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonErzeugenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonErzeugen)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(buttonErzeugen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(de.unibw.prdg.gui.GeneratorApp.class).getContext().getActionMap(GeneratorView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void changeVerteilung(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_changeVerteilung
        if (comboBoxParameterBeginnVerteilung.getSelectedIndex() == 1) {
            labelParameterBeginnMittel.setVisible(false);
            labelParameterBeginnVarianz.setVisible(false);
            textParameterBeginnVarianz.setVisible(false);
            textParameterBeginnMittel.setVisible(false);
        } else {
            labelParameterBeginnMittel.setVisible(true);
            labelParameterBeginnVarianz.setVisible(true);
            textParameterBeginnVarianz.setVisible(true);
            textParameterBeginnMittel.setVisible(true);
        }
    }//GEN-LAST:event_changeVerteilung

    private void actionBeginnVerteilung(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionBeginnVerteilung
        if (comboBoxParameterBeginnVerteilung.getSelectedIndex() == 1) {
            labelParameterBeginnMittel.setVisible(false);
            labelParameterBeginnVarianz.setVisible(false);
            textParameterBeginnVarianz.setVisible(false);
            textParameterBeginnMittel.setVisible(false);
        } else {
            labelParameterBeginnMittel.setVisible(true);
            labelParameterBeginnVarianz.setVisible(true);
            textParameterBeginnVarianz.setVisible(true);
            textParameterBeginnMittel.setVisible(true);
        }
    }//GEN-LAST:event_actionBeginnVerteilung

    private void comboBoxParameterDauerVerteilungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxParameterDauerVerteilungActionPerformed
        if (comboBoxParameterDauerVerteilung.getSelectedIndex() == 1) {
            labelParameterDauerA.setText("Untere Grenze:");
            labelParameterDauerB.setText("Obere Grenze:");
        } else {
            labelParameterDauerA.setText("Mittelwert:");
            labelParameterDauerB.setText("Varianz:");
        }
    }//GEN-LAST:event_comboBoxParameterDauerVerteilungActionPerformed

    private void buttonErzeugenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonErzeugenActionPerformed
		PseudoRandomDataGenerator generator;
    	File dataFile;
		int jobCount;
		int start;
		int ende;
		long seed;

		double myBeginn;
		double sigmaSqrBeginn;
		int aBegin;
		int bBegin;

		double myDauer;
		double sigmaSqrDauer;
		int aDauer;
		int bDauer;
		
		try {
			 jobCount = Integer.parseInt(jTextField2.getText());
			 start = Integer.parseInt(textZeitraumBeginn.getText());
			 ende = Integer.parseInt(textZeitraumEnde.getText());
			 seed = Integer.parseInt(jTextField1.getText());

			 myBeginn = Double.parseDouble(textParameterBeginnMittel.getText());
			 sigmaSqrBeginn = Double.parseDouble(textParameterBeginnVarianz.getText());
			 aBegin = start;
			 bBegin = ende;

			 myDauer = Double.parseDouble(textParameterDauerA.getText());
			 sigmaSqrDauer = Double.parseDouble(textParameterDauerB.getText());
			 aDauer = Integer.parseInt(textParameterDauerA.getText());
			 bDauer = Integer.parseInt(textParameterDauerB.getText());
    	
    	int returnVal = generatorFileChooser.showSaveDialog(this.getFrame());
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			dataFile = generatorFileChooser.getSelectedFile();
			if (comboBoxParameterBeginnVerteilung.getSelectedIndex() == 0) { // Beginn
																				// Normalverteilt
				if (comboBoxParameterDauerVerteilung.getSelectedIndex() == 0) { // Dauer
																				// Normalverteilt
					generator = new PseudoRandomDataGenerator(jobCount, start, ende, seed, dataFile, myBeginn, sigmaSqrBeginn, myDauer, sigmaSqrDauer);
				} else { // Dauer Uniformverteilt
					generator = new PseudoRandomDataGenerator(jobCount, start, ende, seed, dataFile, myBeginn, sigmaSqrBeginn, aDauer, bDauer);
				}
			} else { // Beginn Uniformverteilt
				if (comboBoxParameterDauerVerteilung.getSelectedIndex() == 0) { // Dauer
																				// Normalverteilt
					generator = new PseudoRandomDataGenerator(jobCount, start, ende, seed, dataFile, myDauer, sigmaSqrDauer);
				} else { // Dauer Uniformverteilt
					generator = new PseudoRandomDataGenerator(jobCount, start, ende, seed, dataFile, aDauer, bDauer);
				}
			}

		}
		} catch (Exception e) {
			e.printStackTrace();
		}


    	
    	
        try {
            for (int i = 0; i < busyIcons.length; i++) {
                Icon icon = busyIcons[i];

            }

        } catch (Exception e) {
        }
        
        
        
         
    }//GEN-LAST:event_buttonErzeugenActionPerformed

    private void textZeitraumBeginnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textZeitraumBeginnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textZeitraumBeginnActionPerformed

    private void textZeitraumEndeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textZeitraumEndeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textZeitraumEndeActionPerformed

    private void textParameterBeginnMittelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textParameterBeginnMittelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textParameterBeginnMittelActionPerformed

    private void textParameterBeginnVarianzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textParameterBeginnVarianzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textParameterBeginnVarianzActionPerformed

    private void textParameterDauerAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textParameterDauerAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textParameterDauerAActionPerformed

    private void textParameterDauerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textParameterDauerBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textParameterDauerBActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonErzeugen;
    private javax.swing.JComboBox comboBoxParameterBeginnVerteilung;
    private javax.swing.JComboBox comboBoxParameterDauerVerteilung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelAnzahl;
    private javax.swing.JLabel labelParameter;
    private javax.swing.JLabel labelParameterBeginn;
    private javax.swing.JLabel labelParameterBeginnMittel;
    private javax.swing.JLabel labelParameterBeginnVarianz;
    private javax.swing.JLabel labelParameterDauer;
    private javax.swing.JLabel labelParameterDauerA;
    private javax.swing.JLabel labelParameterDauerB;
    private javax.swing.JLabel labelZeitraum;
    private javax.swing.JLabel labelZeitraumBeginn;
    private javax.swing.JLabel labelZeitraumEnde;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panelParameter;
    private javax.swing.JPanel panelZeitraum;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JTextField textParameterBeginnMittel;
    private javax.swing.JTextField textParameterBeginnVarianz;
    private javax.swing.JTextField textParameterDauerA;
    private javax.swing.JTextField textParameterDauerB;
    private javax.swing.JTextField textZeitraumBeginn;
    private javax.swing.JTextField textZeitraumEnde;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
